-- S3 file storage migration
ALTER TABLE "User"
  DROP COLUMN IF EXISTS "avatarFileId",
  ADD COLUMN IF NOT EXISTS "avatarUrl" TEXT;

ALTER TABLE "FeedPostMedia"
  DROP COLUMN IF EXISTS "fileId",
  ADD COLUMN IF NOT EXISTS "imageUrl" TEXT;

ALTER TABLE "HousingImage"
  DROP COLUMN IF EXISTS "fileId",
  ADD COLUMN IF NOT EXISTS "imageUrl" TEXT;

ALTER TABLE "RestaurantImage"
  DROP COLUMN IF EXISTS "fileId",
  ADD COLUMN IF NOT EXISTS "imageUrl" TEXT;

ALTER TABLE "Story"
  DROP COLUMN IF EXISTS "fileId",
  ADD COLUMN IF NOT EXISTS "mediaUrl" TEXT NOT NULL DEFAULT '';

ALTER TABLE "Message"
  DROP COLUMN IF EXISTS "fileId",
  ADD COLUMN IF NOT EXISTS "imageUrl" TEXT;

ALTER TABLE "BadgeDocument"
  DROP COLUMN IF EXISTS "fileId",
  ADD COLUMN IF NOT EXISTS "documentKey" TEXT;

ALTER TABLE "EventImage"
  DROP COLUMN IF EXISTS "fileId",
  ADD COLUMN IF NOT EXISTS "imageUrl" TEXT;

DROP TABLE IF EXISTS "File";
